server:
  port: 9453
  servlet:
    context-path: /v1/linebotserver

spring:
  application:
    name: "linebot"
  datasource:
    url: ""

line.bot:
  channel-token: 'Put Your Channel Token Here.'
  channel-secret: 'Put Your Channel Secret Here.'
  handler.path: /callback